namespace Scouting.API.Shared;

public static class ErrorCodes
{
    // Common
    public const string COMMON_MESSAGE_VALUE_EMPTY = "COMMON_MESSAGE_VALUE_EMPTY";
    public const string COMMON_MESSAGE_RECORD_NOT_FOUND = "COMMON_MESSAGE_RECORD_NOT_FOUND";
    public const string COMMON_MESSAGE_INVALID_VALUE = "COMMON_MESSAGE_INVALID_VALUE";
    public const string COMMON_MESSAGE_VALUE_MAX_LENGHT_ERROR = "COMMON_MESSAGE_VALUE_MAX_LENGHT_ERROR";
    public const string COMMON_MESSAGE_ALREADY_EXISTS = "COMMON_MESSAGE_ALREADY_EXISTS";
    public const string COMMON_MESSAGE_UNAUTHORIZED = "COMMON_MESSAGE_UNAUTHORIZED";
    public const string COMMON_MESSAGE_FORBIDDEN = "COMMON_MESSAGE_FORBIDDEN";

    // Player
    public const string PLAYER_ALREADY_APPROVED = "PLAYER_ALREADY_APPROVED";
    public const string PLAYER_NOT_PENDING = "PLAYER_NOT_PENDING";

    // Analysis
    public const string ANALYSIS_CONTENT_TOO_SHORT = "ANALYSIS_CONTENT_TOO_SHORT";
    public const string ANALYSIS_NOT_PENDING = "ANALYSIS_NOT_PENDING";

    // Auth
    public const string AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS";
    public const string AUTH_EMAIL_ALREADY_EXISTS = "AUTH_EMAIL_ALREADY_EXISTS";
    public const string AUTH_USERNAME_ALREADY_EXISTS = "AUTH_USERNAME_ALREADY_EXISTS";

    // Vote
    public const string VOTE_PLAYER_NOT_APPROVED = "VOTE_PLAYER_NOT_APPROVED";

    // Follow
    public const string FOLLOW_CANNOT_FOLLOW_YOURSELF = "FOLLOW_CANNOT_FOLLOW_YOURSELF";
    public const string FOLLOW_ALREADY_FOLLOWING = "FOLLOW_ALREADY_FOLLOWING";
    public const string FOLLOW_NOT_FOLLOWING = "FOLLOW_NOT_FOLLOWING";
}
