namespace Scouting.Web.Services;

/// <summary>
/// Stub implementation of IAIAnalysisService.
/// Computes rule-based scores locally until AWS Bedrock is configured.
///
/// To switch to the real Claude implementation:
///   1. Add AWSSDK.BedrockRuntime NuGet package
///   2. Set env vars: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION, Bedrock__ModelId
///   3. Register BedrockAIAnalysisService in DependencyRegistration instead of this stub
/// </summary>
public class StubAIAnalysisService : IAIAnalysisService
{
    public Task<AIEvaluationResult> EvaluateAsync(AIAnalysisInput input, CancellationToken ct = default)
    {
        var originalityScore = ComputeOriginalityScore(input);
        var depthScore       = ComputeDepthScore(input);
        var readingMinutes   = EstimateReadingMinutes(input);
        var isDuplicate      = originalityScore <= 1m;

        return Task.FromResult(new AIEvaluationResult
        {
            IsAvailable            = false,   // stub — real AI not connected
            OriginalityScore       = originalityScore,
            DepthScore             = depthScore,
            EstimatedReadingMinutes = readingMinutes,
            Summary                = null,    // generated by Claude in production
            IsPossibleDuplicate    = isDuplicate,
            DuplicateWarning       = isDuplicate
                ? "Bu analiz mevcut bir analize çok benziyor. Lütfen inceleyiniz."
                : null
        });
    }

    // ── Originality: 0-5 ──────────────────────────────────────────────────────
    // 5 → ilk analiz (mevcut yok) — tamamen özgün sayılır
    // Mevcut analizler varsa: örtüşen n-gram oranına göre puan kır
    private static decimal ComputeOriginalityScore(AIAnalysisInput input)
    {
        if (input.ExistingAnalysesContent.Count == 0) return 5m;

        var newTokens = Tokenize(input.GeneralContent);
        if (newTokens.Count == 0) return 1m;

        var maxOverlap = input.ExistingAnalysesContent
            .Select(existing => OverlapRatio(newTokens, Tokenize(existing)))
            .DefaultIfEmpty(0m)
            .Max();

        // overlap 0% → 5p, 25% → 3.75p, 50% → 2.5p, 75% → 1.25p, 100% → 0p
        return Math.Round(Math.Max(0m, 5m * (1m - maxOverlap)), 1);
    }

    // ── Depth / detail: 0-5 ───────────────────────────────────────────────────
    // Reading time (word count @ 200 wpm) gives 0-3 pts; filled sections give 0-2 pts
    private static decimal ComputeDepthScore(AIAnalysisInput input)
    {
        var readingMinutes = EstimateReadingMinutes(input);

        // 1 dk → 1p, 2 dk → 2p, 3+ dk → 3p
        var readingScore = Math.Min(3m, Math.Round(readingMinutes, 1));

        var filledSections = new[]
        {
            input.TechnicalContent, input.TacticalContent,
            input.PhysicalContent, input.StrengthsContent, input.WeaknessesContent
        }.Count(s => !string.IsNullOrWhiteSpace(s));

        // her bölüm 0.4p, max 2p
        var breadthScore = Math.Min(2m, filledSections * 0.4m);

        return Math.Round(readingScore + breadthScore, 1);
    }

    // ── Reading time: total words / 200 wpm ───────────────────────────────────
    private static decimal EstimateReadingMinutes(AIAnalysisInput input)
    {
        var allText = string.Join(" ",
            input.GeneralContent,
            input.TechnicalContent  ?? "",
            input.TacticalContent   ?? "",
            input.PhysicalContent   ?? "",
            input.StrengthsContent  ?? "",
            input.WeaknessesContent ?? "");

        var wordCount = allText.Split(' ', StringSplitOptions.RemoveEmptyEntries).Length;
        return Math.Round(wordCount / 200m, 1);
    }

    // ── Helpers ───────────────────────────────────────────────────────────────
    private static HashSet<string> Tokenize(string text) =>
        text.ToLowerInvariant()
            .Split([' ', '.', ',', '\n', '\r', '!', '?'], StringSplitOptions.RemoveEmptyEntries)
            .Where(w => w.Length >= 4)
            .ToHashSet();

    private static decimal OverlapRatio(HashSet<string> a, HashSet<string> b)
    {
        if (a.Count == 0 || b.Count == 0) return 0m;
        var intersection = a.Count(w => b.Contains(w));
        return (decimal)intersection / Math.Min(a.Count, b.Count);
    }
}
