namespace Scouting.Web.Services;

/// <summary>
/// Stub implementation of IAIAnalysisService.
/// Computes a rule-based quality score locally until AWS Bedrock is configured.
///
/// To integrate AWS Bedrock (Claude Opus):
///   1. Add AWSSDK.BedrockRuntime NuGet package
///   2. Configure AWS credentials (IAM role / env vars: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION)
///   3. Replace this class with BedrockAIAnalysisService that calls:
///      InvokeModelAsync("anthropic.claude-opus-4-6-v1", prompt)
///   4. Register BedrockAIAnalysisService in DependencyRegistration instead of this stub
/// </summary>
public class StubAIAnalysisService : IAIAnalysisService
{
    public Task<AIEvaluationResult> EvaluateAsync(AIAnalysisInput input, CancellationToken ct = default)
    {
        var score = ComputeLocalScore(input);
        var isDuplicate = CheckBasicDuplicate(input);

        return Task.FromResult(new AIEvaluationResult
        {
            IsAvailable = false,   // stub — real AI not connected yet
            Score = score,
            Summary = null,        // AI summary will be generated by Bedrock
            IsPossibleDuplicate = isDuplicate,
            DuplicateWarning = isDuplicate
                ? "Bu analiz mevcut bir analize çok benziyor. Lütfen inceleyiniz."
                : null
        });
    }

    // ── Rule-based quality scoring ─────────────────────────────────────────────
    // Score breakdown (max 10):
    //   Length score   : total content length / 200, capped at 5.0
    //   Breadth score  : 1 point per filled optional section, max 5
    private static decimal ComputeLocalScore(AIAnalysisInput input)
    {
        var totalLength = input.GeneralContent.Length
            + (input.TechnicalContent?.Length ?? 0)
            + (input.TacticalContent?.Length ?? 0)
            + (input.PhysicalContent?.Length ?? 0)
            + (input.StrengthsContent?.Length ?? 0)
            + (input.WeaknessesContent?.Length ?? 0);

        var lengthScore = Math.Min(5m, totalLength / 200m);

        var filledSections = new[] {
            input.TechnicalContent, input.TacticalContent,
            input.PhysicalContent, input.StrengthsContent, input.WeaknessesContent
        }.Count(s => !string.IsNullOrWhiteSpace(s));

        var breadthScore = (decimal)filledSections; // 0–5

        return Math.Round(lengthScore + breadthScore, 1);
    }

    // Basic duplicate detection: exact substring match (> 60% overlap)
    // Real implementation: Claude Opus semantic similarity
    private static bool CheckBasicDuplicate(AIAnalysisInput input)
    {
        if (input.ExistingAnalysesContent.Count == 0) return false;

        var newContent = input.GeneralContent.ToLowerInvariant();
        if (newContent.Length < 100) return false;

        var sample = newContent[..Math.Min(150, newContent.Length)];
        return input.ExistingAnalysesContent
            .Any(existing => existing.ToLowerInvariant().Contains(sample));
    }
}
